#!/bin/bash
dir=$(dirname $(readlink  -f "$0"))
cd $dir

crontab -l > ./data/oldCron
sed '/play-azan/d' ./data/oldCron > ./data/newCron  


./python/azan.py

cat ./data/cronAzan >> ./data/newCron

crontab ./data/newCron
exit 0