#!/bin/bash
dir=$(dirname $(readlink  -f "$0"))
function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}
cd $dir
pb "ip" &> /dev/null 
echo
ip="a"
while ! valid_ip $ip 
do
	ip=$(sudo $dir/pushbullet/getLastPush)
	sleep 1
done

echo $ip
exit 0
