#!/bin/bash
dir=$(dirname $(readlink  -f "$0"))
cd $dir
./stop-mplayer
./play-atte
./set-volume 50
$(mplayer ./audio/3ed.mp3 &> /dev/null)
hour=$(date +%H)
if [ "$hour" -ge 20 ]
then 
    crontab -l > ./data/oldCron
    sed -e '/play-3ed/ s/^#*/#/' -i ./data/oldCron
    crontab ./data/oldCron 
fi
exit 0
