#!/bin/bash
dir=$(dirname $(readlink  -f "$0"))
cd $dir
if [ -n "$3" ]
then
	echo sleep $3
    sleep $3
fi

sig='Sent with <3 by Robo  about.me/rdahamshi'
br='                                '
arg="m \"$1\" $2$br$br$sig"
messer /data/aes/config.json  cat <<< "$arg"  &
messerpid=$!
sleep 20
kill $messerpid
pbme "Sent :) $arg"
