#!/bin/bash
dir=$(dirname $(readlink  -f "$0"))
cd $dir
if [ -n "$3" ]
then
	echo sleep $3
    sleep $3
fi

arg="m \"$1\" $2"
messer /data/aes/config-robo.json  cat <<< $arg  &
messerpid=$!
sleep 20
kill $messerpid
