#!/usr/bin/env python2
import ConfigParser
import time
import json
import requests


apiFile = open('/data/aes/key')
api_key = apiFile.read().strip()

URL = "https://api.pushbullet.com/v2/pushes?modified_after="
ten_seconds_ago = str(time.time() - 10  * 1000)

data = json.loads(requests.get(URL + ten_seconds_ago, auth=(api_key, '')).content)


if "title" in data["pushes"][0]:
    theMsg = data["pushes"][0]["title"]
else:
    theMsg = data["pushes"][0]["body"]

print theMsg
