#!/bin/bash
flag=true
while $flag; do
    awkRes=$(sensors |awk -F"[\+s\.]" '/+[0-9][0-9]/{ if($2 > 83)print $2}' 2> /dev/null )

    if [ -n "$awkRes" ]
    then 
        pbme "pushServer: WARNING ! HIGH TEMP DETECTED !"
        
        flag=false
    fi

    sensors
    free -mh
    vnstat 
    sleep 2
    clear
done
exit 0